### ISSUE TITLE
URL encoding with space character '+' not support

### ISSUE THREAD

**Issue by hukaixuan** [pvcnt/byblos#1]
when query expression contains space(encoded as +)，it failed to render image with error
`java.io.IOException: Unexpected status code [400]: {"status":"error","errorType":"bad_data","error":"1:2: parse error: unexpected character inside braces: '+'"}`
query example:
`https://byblos.fly.dev/api/v1/graph?e=1685250975985&h=500&q=%7B+__name__%3D%22apm%3Aapp%3Asw_service_percentile_p90%3Amax%22%2C+app%3D%22sw-metric%22%2C+cluster%3D%22BJ%22%2C+job%3D%22xcustom%22%2C+project%3D%22console%22%2C+%7D&s=1685249955985&tz=Etc%2FGMT-8&w=1000`

**Comment by pvcnt** [comment]
Good catch, thank you! This should be fixed by now.
